### ISSUE TITLE
Problem "Values have same structure but are not reference-equal:[]"

### ISSUE THREAD

**Issue by AlexQuiaOpus** [CheckiO-Missions/checkio-task-non-unique-elements#31]
Maybe we should change the test from `assert.strictEqual`  to `assert.deepEqual` ?

**Comment by Matt23488** [comment]
I also get the same error, even though I'm using `Array.prototype.splice` to mutate the input array and then return it. I'm not sure what is wrong but clearly the internals are broken here.

**Comment by pulcherriman** [comment]
I have same issue.

`assert.strictEqual()` function checks for reference equivalence.

There is no way these assertion can pass.

To fix this issue, should do as @AlexQuiaOpus says.
